version: '3.3'
services:

  nginx:
    depends_on:
     - kurento
     - playapp
    image: jwilder/nginx-proxy
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/webrtc-showcase.trembit.com.conf.d:/etc/nginx/conf.d
      - ./web/dist:/etc/nginx/html/static
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/htpasswd:/etc/nginx/htpasswd
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 5084:5084
#      - 8889:8889

  playapp:
    build: .
    ports:
     - 9000:9000

  kurento:
    image: kurento/kurento-media-server:6.7.0-trusty
    ports:
     - 8888:8888
    environment:
     - KMS_STUN_IP=stun4.l.google.com
     - KMS_STUN_PORT=19302
     - KMS_TURN_URL=webrtc@live.com:muazkh@numb.viagenie.ca

networks:
  default:
#    driver: overlay

#  coturn:
##    build: coturn
#    image: kurento/coturn
#    ports:
#      - "3478:3478/udp"
#    environment:
#     - NAT=true
#
#  letsencrypt:
#    image: jrcs/letsencrypt-nginx-proxy-companion
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#    volumes_from:
#      - nginx

#  nginx1:
#    image: jrcs/letsencrypt-nginx-proxy-companion
#    ports:
#      - "80:80"
#      - "443:443"
#     environment:
#      - VIRTUAL_HOST=meetings-bootstrap.trembit.com
