version: '2'
services:

  nginx:
    depends_on:
     - playapp
    build: ./nginx
    volumes:
#      - ./nginx/certs:/etc/nginx/certs
      - ./web/dist:/etc/nginx/html/static
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/htpasswd:/etc/nginx/htpasswd
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 5085:443
#      - 443:443
#      - 80:80

  playapp:
    depends_on:
     - kurento
    build: .
    ports:
     - 9000:9000
    volumes:
     - ./.ivy2:/root/.ivy2
     - ./.sbt:/root/.sbt

  kurento:
    image: kurento/kurento-media-server:6.7.0-trusty
    ports:
     - 8888:8888
    environment:
    # Check STUN/TURN server with https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
     - KMS_STUN_IP=stun:stun.xten.com
     - KMS_STUN_PORT=3478
#     - KMS_TURN_URL=webrtc@live.com:muazkh@numb.viagenie.ca

##networks:
#  default:
#    driver: overlay

#  coturn:
##    build: coturn
#    image: kurento/coturn
#    ports:
#      - "3478:3478/udp"
#    environment:
#     - NAT=true
#
#  letsencrypt:
#    image: jrcs/letsencrypt-nginx-proxy-companion
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#    volumes_from:
#      - nginx

#  nginx1:
#    image: jrcs/letsencrypt-nginx-proxy-companion
#    ports:
#      - "80:80"
#      - "443:443"
#     environment:
#      - VIRTUAL_HOST=meetings-bootstrap.trembit.com
