version: '2.0'
services:

  nginx:
    depends_on:
     - kurento
    image: jwilder/nginx-proxy
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/proxy.conf.nginx:/etc/nginx/conf.d/my_proxy.conf
      - ./nginx/web:/usr/share/nginx/html
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/htpasswd:/etc/nginx/htpasswd
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
      - 8889:8889

  kurento:
    image: kurento/kurento-media-server:6.6.3
    ports:
     - 8888:8888
    environment:
     - KMS_STUN_IP=stun4.l.google.com
     - KMS_STUN_PORT=19302
     - KMS_TURN_URL=webrtc@live.com:muazkh@numb.viagenie.ca

#  coturn:
##    build: coturn
#    image: kurento/coturn
#    ports:
#      - "3478:3478/udp"
#    environment:
#     - NAT=true
#
#  letsencrypt:
#    image: jrcs/letsencrypt-nginx-proxy-companion
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#    volumes_from:
#      - nginx

#  nginx1:
#    image: jrcs/letsencrypt-nginx-proxy-companion
#    ports:
#      - "80:80"
#      - "443:443"
#     environment:
#      - VIRTUAL_HOST=meetings-bootstrap.trembit.com
